default:
  interruptible: true
  image: node:16.13.2-alpine
  before_script:
    - npm i -g pnpm@6.x
    - pnpm config set store-dir .pnpm-store
    - apk add bash

stages:
  - setup
  - build
  - test
  - deploy_dev
  - deploy_prod

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always 

.dependencies_cache:
  cache:
    key:
      files:
        - pnpm-lock.yml
    paths:
        - .npm
        - .pnpm-store
        - node_modules
        - 'packages/*/node_modules'
        - 'packages/*/.npm'    
    policy: pull
    when: on_success

setup:
  stage: setup
  script:
    - pnpm i --ignore-scripts
  extends: .dependencies_cache
  allow_failure: false
  cache:
    policy: pull-push

build-all:
  stage: build
  script:
    - pnpm run build
  needs:
    - setup
  extends: .dependencies_cache
  artifacts:
    paths:
      - packages/**/*
    expire_in: 1h
  allow_failure: false
  when: on_success     


