name: Checks

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies and tests
        run: | # Install and link dependencies
          npm ci

      - name: build code
        run: | # Install and link dependencies
          npm run build

       - name: run tests
         run: | # Install and link dependencies
          npm run test
